---
- name: Install necesary packages on Red Hat base families
  package:
    name: "{{ item }}"
    state: present
  loop:
    - openscap-scanner
    - scap-security-guide
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - setup

- name: Install necesary packages on Debian base systems
  package:
    name: "{{ item }}"
    state: present
  loop:
    - libopenscap8
  when: ansible_facts['os_family'] == "Debian"
  tags:
    - setup

- name: Copy datastream
  copy:
    src: "{{ ds_location }}{{ ssg_file }}"
    dest: "{{ ssg_dir }}"
  tags:
    - setup
