- hosts: "{{ target | default('master') }}"
  #become: yes
  vars:
    local_user: ansible # ansible user
    days: "30"
    user: "jose"
  tasks:
    - name: Generate a key
      shell: openssl genrsa -out {{ user }}.key 2048

    - name: Generate a CSR
      shell: openssl req -new -key {{ user }}.key -out {{ user }}.csr -subj "/CN={{ user }}/O=k8s"

    - name: Generate the CRT
      become: yes
      become_user: "{{ local_user }}"
      shell: sudo openssl x509 -req -in {{ user }}.csr -CA /etc/kubernetes/pki/ca.crt -CAkey /etc/kubernetes/pki/ca.key -CAcreateserial -out {{ user }}.crt -days {{ days }}

    - name: set crt var
      shell:  cat {{ user }}.crt  | base64  | tr -d "\n"
      register: cert_command

    - name: change file permissions
      become: yes
      become_user: "{{ local_user }}"
      shell: sudo chown {{ local_user }}:{{ local_user }} {{ item }}
      loop:
        - "{{ user }}.crt"
        - "{{ user }}.key"

    - set_fact:
        client_crt: "{{ cert_command.stdout }}"

    - name: set key var
      shell:  cat {{ user }}.key  | base64  | tr -d "\n"
      register: key_command

    - set_fact:
        client_key: "{{ key_command.stdout }}"

    - name: copy the default config file
      template:
        src: ../templates/k8s.conf
        dest: /home/{{ local_user }}/{{ user }}-default.conf
