- name: Playbook to install and configure longhorn
  hosts: "{{ target | default('master') }}"
  vars:
    local_user: ansible # ansible user
    values_yaml: longhorn.yaml
  tasks:
    - name: Longhorn Install | Check if longhorn is present
      stat:
        path: /home/{{ local_user }}/longhorn.log
      register: result

    - name: Longhorn Install | copy the {{ values_yaml }}
      copy:
        src: ../templates/{{ values_yaml }}
        dest: /home/{{ local_user }}/
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
      when: not result.stat.exists

    - name: Longhorn Install | Apply longhorn yaml
      shell: kubectl apply -f  {{ values_yaml }} > longhorn.log
      args:
        chdir: "/home/{{ local_user }}"
        creates: longhorn.log
      when: not result.stat.exists

    - name: Longhorn Install | clean up
      file:
        path: /home/{{ local_user }}/{{ values_yaml }}
        state: absent
