- hosts: "{{ target | default('master') }}"
  become: yes
  vars:
    local_user: ansible # ansible user
    kvip: "192.168.100.77" # virtual IP for kube-vip
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    # for adding a master
    - name: get join command master
      shell:  kubeadm init phase upload-certs --upload-certs
      register: join_command_master

    - name: set join command master
      set_fact:
        join_command_master: "{{ join_command_master.stdout_lines[2] }}"



#- hosts: "{{ target | default('control_planes') }}" # edit only new master list
- hosts: localhost
  become: yes
  vars:
    local_user: ansible
    kvip: "192.168.100.77" # virtual IP for kube-vip
  tasks:
    - name: Copy the default kube-vip yml file
      become: yes
      template:
        src: ../templates/kube-vip.j2
        dest: /etc/kubernetes/manifests/kube-vip.yaml
        owner: root
        group: root
        mode: "0644"
      tags:
        - test 
 
    - name: Wait for TCP port 6443 on kube-vip to be reachable from others control plane
      wait_for: "host={{ kvip }} port=6443 timeout=1"

    - name: join cluster
      shell: "{{ hostvars['k8s-control-plane'].join_command }} --control-plane --certificate-key {{ hostvars['k8s-control-plane'].join_command_master }} >> node_joined.log"
      args:
        chdir: /home/{{ local_user }}
        creates: node_joined.log
