

    - name: Longhorn Setup | start and enable open-iscsi
      service:
        name: iscsid
        state: started
        enabled: yes
      tags:
        - longhorn

    - name: Longhorn Setup | create an empty file for the LongHorn module
      copy:
        content: ""
        dest: /etc/modules-load.d/longhorn.conf
        force: no
      tags:
        - longhorn


    - name: Longhorn Setup | configure modules for LongHorn
      blockinfile:
        path: /etc/modules-load.d/longhorn.conf
        block: |
             uio
             uio_pci_generic
             nvme-tcp
      tags:
        - longhorn


    - name: Longhorn Setup | load uio and uio_pci_generic
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - uio
        - uio_pci_generic
        - nvme-tcp
      tags:
        - longhorn


    - name: Longhorn Setup | allocate huge pages
      shell: "echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages"
      changed_when: false
      ignore_errors: yes
      tags:
        - longhorn

      
    - name: Longhorn Setup | make the change permanent
      shell: echo "vm.nr_hugepages=1024" >> /etc/sysctl.conf
      changed_when: false
      ignore_errors: yes
      tags:
        - longhorn

